server.directory=../../../../server
server.jar=spigot-1.8.8.jar
java.home=auto
heap.minimum=1G
heap.maximum=2G
analytics.framework=../..
analytics.python=python
analytics.raw=../../../../../datasets/raw
